config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get  '/users/fast', to: 'users/fast#new',              as: :user_fast
    put  '/users/fast', to: 'users/fast#new_session',      as: :user_fast_session
    post '/users/fast', to: 'users/fast#new_registration', as: :user_fast_registration
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :books, only: :show do
    member do
      post :add_to_cart
    end
  end

  scope path: 'categories' do
    get '/',    to: 'categories#show', as: :categories
    get '/:id', to: 'categories#show', as: :category
  end

  scope :cart do
    get    '/', to: 'cart#edit', as: :cart
    post   '/', to: 'cart#update', as: :update_cart
    post   '/book/:id', to: 'cart#add_product', as: :cart_add_product
    delete '/book/:id', to: 'cart#remove_product', as: :cart_remove_product
  end

  # resource :cart, only: [:show]
  resources :orders, only: [:index, :edit]

  resources :order_item, only: [:create, :update, :destroy]
  resources :checkout, only: [:show, :update]

  # resource :cart_item, controller: :order_item, only: [:create, :update, :destroy]
  # post   '/:class/:id', to: 'cart#add_product',    as: :cart_add_product
  # delete '/:class/:id', to: 'cart#remove_product', as: :cart_remove_product
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  respond_to :js, only: [:add_product]

  def edit
    present CartPage::CartPresenter.new
  end

  def update
    @cart = CartForm.from_params(params)
    CartPage::UpdateCart.call(@cart) do
      on(:invalid_coupon)  { flash[:error] = 'Invalid coupon code' }
      on(:invalid_product) { flash[:error] = 'Invalid product quantity' }
      on(:ok)              { flash[:success] = 'Cart was updated successfully' }
    end
    present CartPage::CartPresenter.new(@cart)
    render :edit
  end

  def remove_product
    CartPage::RemoveProduct.call(id: params[:id]) do
      on(:invalid_product) { redirect_to cart_path, error: 'Invalid product' }
      on(:ok)              { redirect_to cart_path }
    end
  end

  def add_product
    CartPage::AddProduct.call(id: params[:id], quantity: 1) do
      on(:invalid_product) do
        redirect_to :root, flash: { error: 'Invalid product' }, js: true
        return
      end
    end
  end
end

app/views/cart/_products.html.haml
%table.table.table-hover
  %tr.no-hover
    %th.col-pic.pl-0
      %span.in-grey-600 Product
    %th.col-title
    %th.col-price
      %span.in-grey-600 Price
    %th.col-quantity
      %span.in-grey-600 Quantity
    %th.col-total
      %span.in-grey-600 SubTotal
    %th.col-close
  - products.each do |product|
    = fields_for 'products[]', product do |product_fields|
      = product_fields.hidden_field :id
      %tr
        %td
          .general-img-wrap-table
            = image_tag product.cover, class: 'cart-img-shadow pull-left width-full'
        %td
          %p.title= product.title
        %td
          %span.font-16.in-gold-500= product.price
        %td
          .input-group.general-position{class: product.error_class, data: {quantity: true}}
            %a.input-link{href: "#"}
              %i.fa.fa-minus.line-height-40
            = product_fields.text_field :quantity, class: 'form-control quantity-input'
            %a.input-link{href: "#"}
              %i.fa.fa-plus.line-height-40
        %td
          %span.font-16.in-gold-500= product.subtotal
        %td
          = link_to cart_remove_product_path(product), method: :delete, class: 'close general-cart-close' do
            %span{'aria-hidden': "true"} &times;

app/views/cart/_products_xs.html.haml
- presenter.products.each do |product|
  .general-cart-item.divider-lg-bottom
    %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
      %span{'aria-hidden': "true"} &times;
    .general-img-wrap-table
      = image_tag product.cover, class: 'cart-img-shadow'
    %p.title= product.title
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500= product.price
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          = quantity_widget(product)
          -# .input-group
          -#   %a.input-link{href: "#"}
          -#     %i.fa.fa-minus.line-heaght-40
          -#   %input.form-control.quantity-input{type: "text"}
          -#   %a.input-link{href: "#"}
          -#     %i.fa.fa-plus.line-heaght-40
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500= product.subtotal

app/views/cart/add_product.js.haml
- partial = render partial: 'layouts/shared/cart'
:plain
  $('#cart').html('#{escape_javascript(partial)}');

app/views/cart/edit.html.haml
%h1.general-title-margin Cart
= form_tag update_cart_path do
  - if presenter.cart_empty?
    %h2.text-center.mt-10.mb-40 Cart is empty
  - else
    -# .hidden-xs
    = render partial: 'products', locals: { products: presenter.products }
    -# .visible-xs
    -#   = render partial: 'products_xs', locals: { products: presenter.products }
  .general-order-wrap
    .row
      .col-sm-4
        = fields_for 'coupon', presenter.coupon do |coupon_fields|
          .form-group.general-input-group{class: presenter.coupon.error_class}
            = label_tag 'coupon_code', 'Enter Your Coupon Code', class: 'control-label'
            = coupon_fields.text_field :code, placeholder: 'Enter Your Coupon Code', class: 'form-control'
            - if presenter.coupon.helper?
              %span.help-block= presenter.coupon.helper
          %div
            -# %button.btn.btn-primary.mr-5.mb-15.visible-xs-inline-block Apply Coupon
            = button_tag 'Update Cart', class: 'btn btn-primary mt-30 mb-15 res-block'
      .col-sm-8
        .text-center.general-text-right
          %p.in-gold-500.font-18 Order Summary
          %table.general-summary-table.general-summary-table-right.general-text-right
            %tr
              %td
                %p.font-16 Subtotal:
              %td
                %p.font-16= presenter.subtotal
            %tr
              %td
                %p.font-16 Coupon:
              %td
                %p.font-16= presenter.saved
            %tr
              %td
                %strong.font-18 Order Total:
              %td
                %strong.font-18= presenter.order_total
          = link_to 'Checkout', checkout_path(:address), class: 'btn btn-default mb-20 visible-xs-inline-block'
- unless presenter.cart_empty?
  = button_to 'Checkout', checkout_path(:address), method: :get, class: 'btn btn-default mb-20 hidden-xs center-block'