config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get  '/users/fast', to: 'users/fast#new',              as: :user_fast
    put  '/users/fast', to: 'users/fast#new_session',      as: :user_fast_session
    post '/users/fast', to: 'users/fast#new_registration', as: :user_fast_registration
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :books, only: :show do
    member do
      post :add_to_cart
    end
  end

  scope path: 'categories' do
    get '/',    to: 'categories#show', as: :categories
    get '/:id', to: 'categories#show', as: :category
  end

  scope :cart do
    get    '/', to: 'cart#edit', as: :cart
    post   '/', to: 'cart#update', as: :update_cart
    post   '/book/:id', to: 'cart#add_product', as: :cart_add_product
    delete '/book/:id', to: 'cart#remove_product', as: :cart_remove_product
  end

  # resource :cart, only: [:show]
  resources :orders, only: [:index, :edit]

  resources :order_item, only: [:create, :update, :destroy]
  resources :checkout, only: [:show, :update]

  # resource :cart_item, controller: :order_item, only: [:create, :update, :destroy]
  # post   '/:class/:id', to: 'cart#add_product',    as: :cart_add_product
  # delete '/:class/:id', to: 'cart#remove_product', as: :cart_remove_product
end

app/views/layouts/shared/_cart.html.haml
%span.shop-icon<
  - unless current_order.order_items.empty?
    %span.shop-quantity= current_order.order_items.size

app/views/layouts/shared/_flash.html.haml
- flash.each do |name, msg|
  #flash{ :class => "alert alert-#{name}"}
    .container
      %button.close{ data: { dismiss: "alert" } } &times;
      = msg

app/views/layouts/shared/_footer.html.haml
%footer.navbar.navbar-inverse.mb-0
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            %a.nav-link{  href: '#' } Home
          %li
            %a.nav-link{  href: '#' } Shop
          %li
            %a.nav-link{  href: '#' } Orders
          %li
            %a.nav-link{  href: '#' } Settings
      .col-sm-3
        %p.general-nav-mail support@bookstore.com
        %p.general-nav-number (555)-555-5555
        %ul.list-inline.general-align
          %li
            %a.nav-link{  href: '#' }
              %i.fa.fa-facebook{  'aria-hidden': 'true' }
          %li
            %a.nav-link{  href: '#' }
              %i.fa.fa-twitter{  'aria-hidden': 'true' }
          %li
            %a.nav-link{  href: '#' }
              %i.fa.fa-google-plus{  'aria-hidden': 'true' }
          %li
            %a.nav-link{  href: '#' }
              %i.fa.fa-instagram{  'aria-hidden': 'true' }

app/views/layouts/shared/_header.html.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left.ml-15{ type: 'button', data: { toggle: 'collapse', target: '#navbar' } }
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Bookstore', root_path, class: 'navbar-brand'
    = link_to cart_path, class: 'shop-link pull-right', id: 'cart' do
      = render partial: 'layouts/shared/cart'
    .navbar-collapse.collapse.pl-30#navbar{ aria: { expanded: 'false' } }
      %button.close.visible-xs{ type: 'button', aria: { label: 'Close' }, data: { toggle: 'collapse', target: '#navbar' } }
        %span{ aria: { hidden: 'true' } } &times;
      %ul.nav.navbar-nav
        %li= link_to 'Home', root_path
        %li.dropdown
          =link_to 'Shop', categories_path, class: 'dropdown-toggle', role: 'button', data: { toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }
          %ul.dropdown-menu
            - presenter(:header).categories.each do |category|
              %li= link_to category.title, category
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{ href: '#', role: 'button', data: { toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' } } My account
            %ul.dropdown-menu
              %li= link_to 'Orders', '#'
              %li= link_to 'Settings', '#'
              %li.divider
              - if current_user.is_admin
                %li= link_to 'Admin page', rails_admin_path
              %li= link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Log in', new_user_session_path
          %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/shared/_yotpo.html.haml
-# TODO: fix, yotpo tampering styles, e.g. h1 on book page
:javascript
  (function e() {
      var e = document.createElement("script");
      e.type = "text/javascript";
      e.async = true;
      e["data-turbolinks-track"] = 'reload'
      e.src = "//staticw2.yotpo.com/#{ENV['YOTPO_KEY']}/widget.js";
      var t = document.getElementsByTagName("script")[0];
      t.parentNode.insertBefore(e, t)
  })();
  document.addEventListener("turbolinks:load", function() {
    if (window.yotpo) { yotpo.initWidgets() }
  })