config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get  '/users/fast', to: 'users/fast#new',              as: :user_fast
    put  '/users/fast', to: 'users/fast#new_session',      as: :user_fast_session
    post '/users/fast', to: 'users/fast#new_registration', as: :user_fast_registration
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :books, only: :show do
    member do
      post :add_to_cart
    end
  end

  scope path: 'categories' do
    get '/',    to: 'categories#show', as: :categories
    get '/:id', to: 'categories#show', as: :category
  end

  scope :cart do
    get    '/', to: 'cart#edit', as: :cart
    post   '/', to: 'cart#update', as: :update_cart
    post   '/book/:id', to: 'cart#add_product', as: :cart_add_product
    delete '/book/:id', to: 'cart#remove_product', as: :cart_remove_product
  end

  # resource :cart, only: [:show]
  resources :orders, only: [:index, :edit]

  resources :order_item, only: [:create, :update, :destroy]
  resources :checkout, only: [:show, :update]

  # resource :cart_item, controller: :order_item, only: [:create, :update, :destroy]
  # post   '/:class/:id', to: 'cart#add_product',    as: :cart_add_product
  # delete '/:class/:id', to: 'cart#remove_product', as: :cart_remove_product
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :authorships, dependent: :destroy
  has_many :authors, through: :authorships
  has_many :covers, dependent: :destroy
  has_many :order_items, dependent: :destroy

  validates :title, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.00 }, presence: true
  validates :description, length: { maximum: 500 }

  before_save do
    materials&.capitalize!
    description&.capitalize!
  end

  def create_associated_image(image)
    covers.create(file: image)
  end

  def to_s
    title
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource only: [:show]

  def show
    item = current_order.order_items.find_by(book: @book)
    current_quantity = item&.quantity || 1
    present BookPage::BookPresenter.new(book: @book, quantity: current_quantity)
  end

  def add_to_cart
    form = ProductForm.from_params(params)
    BookPage::AddToCart.call(form) do
      on(:invalid_product, :invalid_quantity) do |errors|
        flash[:error] = errors.first
      end
      on(:ok) { flash[:notice] = 'Book was added' }
    end

    redirect_to book_path(id)
  end

  private

  def id
    params[:id]
  end
end

app/views/books/_add_to_cart_link.html.haml
- url = cart_add_product_path(book)
= link_to url, method: :post, remote: true, class: 'thumb-hover-link' do
  %i.fa.fa-shopping-cart.thumb-icon

app/views/books/_thumb.html.haml
.general-thumb-wrap
  .thumbnail.general-thumbnail
    = image_tag book.cover, class: 'img-shadow general-thumbnail-img'
    .thumb-hover
      .general-thumb-link-wrap
        = link_to book, class: 'thumb-hover-link' do
          %i.fa.fa-eye.thumb-icon{'aria-hidden': "true"}
        = render partial: 'books/add_to_cart_link', locals: { book: book }
.general-thumb-info
  %p.title= book.title
  %p.font-16.in-gold-500= number_to_currency(book.price)
  %span.divider-sm
  %p.in-grey-600.small= book.authors_names

app/views/books/show.html.haml
= link_to :back, class: 'general-back-link' do
  %i.fa.fa-long-arrow-left.mr-15
  Back to results

.row
  .col-sm-6
    .product-gallery
      .mb-20
        = image_tag presenter.book.primary_cover, class: 'img-responsive img-shadow'
      - if presenter.book.minor_covers?
        .images.clearfix
          - presenter.book.minor_covers.each do |cover|
            = link_to '#', class: 'img-link' do
              = image_tag cover, class: 'width-full'
  .col-sm-6
    %h1.mt-res-0= presenter.book.title
    %p.in-grey-600.small= presenter.book.authors_names
    .row
      .col-xs-12.col-md-4
        %p.h1.in-gold-500.mt-10= presenter.book.price
      = form_tag add_to_cart_book_path(presenter.book), method: :post do
        .col-xs-5.col-md-3
          .input-group.general-position{data: {quantity: true}}
            %a.input-link{href: "#"}
              %i.fa.fa-minus.line-height-40
            = text_field_tag :quantity, presenter.quantity, class: 'form-control quantity-input'
            %a.input-link{href: "#"}
              %i.fa.fa-plus.line-height-40
          -# = quantity_widget(presenter.book, book_fields)
        .col-xs-7.col-md-5
          = button_tag 'Add to Cart', class: 'btn btn-default pull-right general-position'
    .general-info-wrap.divider-lg
      %p Description
      = presenter.description
    .general-info-wrap.divider-lg
      .clearfix
        %p.pull-left Year of publication
        %p.in-grey-600.small.pull-right= presenter.book.publication_year
    .general-info-wrap.divider-lg
      .clearfix
        %p.pull-left Dimensions
        %p.in-grey-600.small.pull-right= presenter.book.dimensions
    .general-info-wrap.divider-lg
      .clearfix
        %p.pull-left Materials
        %p.in-grey-600.small.pull-right= presenter.book.materials

.mb-80
  = presenter.review_widget